# Generated by Django 2.1.7 on 2019-05-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='¿Visto?'),
        ),
        migrations.AddField(
            model_name='inboxmessage',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='¿Visto?'),
        ),
    ]
