# Generated by Django 2.1.7 on 2019-05-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190506_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='inboxmessage',
            name='is_seen',
        ),
    ]
