# Generated by Django 2.1.7 on 2019-05-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190507_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='¿Visto?'),
        ),
    ]
