# Generated by Django 2.1.7 on 2019-05-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conversation_is_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='is_seen',
        ),
        migrations.AddField(
            model_name='inboxmessage',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='¿Visto?'),
        ),
    ]
