# Generated by Django 2.1.7 on 2019-05-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190514_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmessage',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='visto'),
        ),
    ]
