# Generated by Django 2.1.7 on 2019-05-15 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_inboxmessage_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboxmessage',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='inboxmessage',
            name='seen',
        ),
    ]
