# Generated by Django 2.1.7 on 2019-05-23 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190523_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressproperty',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_addresspropertys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addressproperty',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_addresspropertys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adminprofiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_adminprofiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='catalogservice',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalogservices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='catalogservice',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_catalogservices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactproperty',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contactpropertys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactproperty',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contactpropertys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacttypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contacttypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inboxmessage',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inboxmessages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inboxmessage',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inboxmessages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ownerprofiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ownerprofiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_paymenttypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_paymenttypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_postattachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_postattachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_postcategorys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_postcategorys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_propertys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_propertys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyinterior',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_propertyinteriors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyinterior',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_propertyinteriors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyinteriorhasservice',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_propertyinteriorhasservices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyinteriorhasservice',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_propertyinteriorhasservices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertypreferences',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_propertypreferencess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertypreferences',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_propertypreferencess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sitepreferencess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitepreferences',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sitepreferencess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
