# Generated by Django 2.1.7 on 2019-05-23 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190523_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cell_phone',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{8,10}$')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{8,10}$')], verbose_name='Teléfono'),
        ),
    ]
