# Generated by Django 2.1.7 on 2019-05-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_emailmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='conversation',
            name='message_footer',
            field=models.TextField(default='Thanks', max_length=1000),
        ),
        migrations.AddField(
            model_name='conversation',
            name='message_from',
            field=models.TextField(default='You have recieved a message from:', max_length=1000),
        ),
        migrations.AddField(
            model_name='conversation',
            name='message_name',
            field=models.CharField(default='Message', max_length=100),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='Welcome To Comovi', max_length=100),
        ),
        migrations.DeleteModel(
            name='EmailMessage',
        ),
    ]
