# Generated by Django 2.1.7 on 2019-05-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190527_0441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='message_name',
            new_name='message_body_name',
        ),
        migrations.AddField(
            model_name='conversation',
            name='message_footer_comovi',
            field=models.TextField(default='Comovi Support Team', max_length=1000),
        ),
    ]
