# Generated by Django 2.1.7 on 2019-05-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190527_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='name_of_template',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
