# Generated by Django 2.1.7 on 2019-05-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_conversation_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='message_body_name',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='message_footer',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='message_footer_comovi',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='message_from',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='title',
        ),
    ]
