# Generated by Django 2.1.7 on 2019-05-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_selectemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectemail',
            name='name_of_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CommonEmailTemplate'),
        ),
    ]
