# Generated by Django 2.1.7 on 2019-05-28 12:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190528_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectemail',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Foreign Key (type determined by related field)'),
        ),
    ]
