# Generated by Django 2.1.7 on 2019-05-29 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_commonemailtemplate_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonemailtemplate',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Conversation'),
        ),
    ]
