# Generated by Django 2.1.7 on 2019-05-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_commonemailtemplate_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectemail',
            name='Mail_name',
            field=models.CharField(default='wrtite the mail Name', max_length=100),
        ),
    ]
