# Generated by Django 2.1.7 on 2019-05-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_emailmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='content',
            new_name='content1',
        ),
    ]
