# Generated by Django 2.1.7 on 2019-05-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20190529_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonemailtemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='commonemailtemplate',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='selectemail',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='selectemail',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='selectemail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='content',
        ),
        migrations.DeleteModel(
            name='CommonEmailTemplate',
        ),
        migrations.DeleteModel(
            name='SelectEmail',
        ),
    ]
