# Generated by Django 2.1.7 on 2019-05-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_emailmessage_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='post',
            new_name='prop_inter',
        ),
    ]
