# Generated by Django 2.1.7 on 2019-05-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20190529_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='prop_inter',
            new_name='property_interior',
        ),
    ]
