# Generated by Django 2.1.7 on 2019-05-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20190529_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='prop_inter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_notice', to='core.PropertyInterior'),
        ),
    ]
