# Generated by Django 2.1.7 on 2019-05-29 09:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('date_modification', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('content1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='core.Conversation')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_emailtemplates', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_emailtemplates', to=settings.AUTH_USER_MODEL)),
                ('prop_inter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_notice', to='core.PropertyInterior')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='prop_inter',
        ),
        migrations.DeleteModel(
            name='EmailMessage',
        ),
    ]
