# Generated by Django 2.1.7 on 2019-05-29 09:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20190529_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('date_modification', models.DateTimeField(auto_now_add=True, null=True)),
                ('name_of_email', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField(default='Fill The templates')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_selectemails', to=settings.AUTH_USER_MODEL)),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.EmailTemplate')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_selectemails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
