# Generated by Django 2.1.7 on 2019-05-30 05:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20190529_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonemailtemplate',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
