# Generated by Django 2.1.7 on 2019-05-30 06:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_commonemailtemplate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='content1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
