# Generated by Django 2.1.7 on 2019-05-30 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_conversation_content1'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='template_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CommonEmailTemplate'),
        ),
    ]
