# Generated by Django 2.1.7 on 2019-05-30 07:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_conversation_template_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonemailtemplate',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='content1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='template_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CommonEmailTemplate'),
        ),
    ]
