# Generated by Django 2.1.7 on 2019-05-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20190530_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='template_name',
        ),
    ]
