# Generated by Django 2.1.7 on 2019-05-31 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20190531_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='template_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welcome', to='core.CommonEmailTemplate'),
        ),
    ]
