# Generated by Django 2.1.7 on 2019-06-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20190531_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='template_name',
        ),
    ]
