# Generated by Django 2.1.7 on 2019-06-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20190603_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content1',
        ),
    ]
