# Generated by Django 2.1.7 on 2019-06-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_post_content1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='prop_inter',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='template_name',
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
