# Generated by Django 2.1.7 on 2019-06-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20190603_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='template_name',
        ),
    ]
