# Generated by Django 2.1.7 on 2019-06-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20190603_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonemailtemplate',
            name='name_of_template',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
