from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from comovi.apps.website.views import *
from comovi.apps.core.views import error404
app_name = 'website'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_reset/', password_reset, name='password_reset'),
    path('my_profile/', EditUserProfileView.as_view(), name='my_profile'),
    path('inbox/', InboxView.as_view(), name='inbox'),
    path('inbox/<uuid:pk>/', InboxDetailView.as_view(), name='inbox_detail'),
    path('inbox/create/', SendEmailView.as_view(), name='send_email'),
    path('inbox/sent/', SentInboxView.as_view(), name='inbox_sent'),
    path('newspaper/', NewspaperView.as_view(), name='newspaper'),
    path('notice/', CreateNotice, name="New_Notice"),
    path('property/<uuid:pk>/', PropertyView.as_view(), name='property'),
    path('property-interior/<uuid:pk>/', PropertyInteriorView.as_view(), name='property_interior'),
    path('payments/', PaymentInteriorView.as_view(), name='payments'),
    path('pay/<uuid:pk>/', PayView.as_view(), name='pay'),
    path('payments/history/', PaymentView.as_view(), name='payment_history'),
    path('page/', PageView.as_view(), name='page'),
    path('language/', LanguageSelect, name="LanguageSelect"),
    path('property-manager/', ProperyManagerView.as_view(), name ='Property_manager' ),
    path('property-interior/<uuid:pk>/property-manager-interiors-details/', PropertyManageInteriors.as_view(), name ='Property_manager_details' ),
    path('property/<uuid:pk>/condinium-manager-details-page/', CondiniumUserManage.as_view(), name='condinium_manager_details'),
    path('interior-detail/<uuid:pk>/', InteriorDetail.as_view(), name="interior-detail"),
    path('update_user_by_id/', UpdateUserById, name="UpdateUserById"),
    path('delete_user_by_id/', DeleteUserById, name="DeleteUserById"),
    path('create_resident_interior/', CreateUserWithResident, name="create_resident_interior"),
    path('create_new_interior/', CreateNewInterior, name="create_new_interior"),
    path('delete_new_interior/', DeleteNewInterior, name="delete_new_interior"),
    path('edit_new_interior/', EditNewInterior, name="edit_new_interior"),
    path('property/<uuid:pk>/property-dashboard/', PropertyDashboard.as_view(), name='Property-Dashboard'),
    path('property/<uuid:pk>/user-display/', UserDisplay.as_view(), name = 'User_Display_Details'),
    path('Property_manager_condonium_profile/<uuid:pk>/', PropertyManagerCondonium.as_view(), name='Condonium_Profile'),
    path('Historic/<uuid:pk>/', HistoricDisplay.as_view(), name='UserData'),
    path('interior/Historic/<uuid:pk>/', InteriorHistoricDisplay.as_view(), name='Interior_user_data'),
    path('property/<uuid:pk>/interior-user-display/', InteriorUserDisplay.as_view(), name = 'interior_User_Display_Details'),
    path('delete_notice/', DeleteNotice, name='DeleteNotice'),
    path('edit_notice/',EditNotice, name='editnotice'),
    path('save_edit_notice/<uuid:id>/', SaveEditNotice, name='save_edit_notice'),
    path('getInteriorServiceDetail/',getInteriorServiceDetail, name='getInteriorServiceDetail'),
    path('updateInteriorService/', updateInteriorService, name="updateInteriorService"),
    path('deleteInteriorService/', deleteInteriorService, name="deleteInteriorService"),
    path('createInteriorService/', createInteriorService, name="createInteriorService"),
    path('modify-date/', updateDate, name="ModifyDate"),
    path('seen_msg/', SeenMsgs, name='SeenMsg'),
    path('Delete-msg/',Deletemsg, name='DeleteMsg'),
    path('seen-news/', SeenNews, name='SeenNews'),
    path('get-data/', GetData, name="get-data"),
    path('add_post_attachment/<uuid:post_id>/', add_post_attachment, name='add_post_attachment'),
    path('tmpp/', Tmpp, name="tmp"),
    path('conversation/<uuid:conv_id>/', ConverstaionView.as_view(), name="conversation"),
    path('error', error404, name='Error'),
    path('email', EmailView.as_view(), name='Email'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
